all:
  hosts:
    node1:
      ansible_host: 192.168.1.194
      ip: 192.168.1.194
      access_ip: 192.168.1.194
    node2:
      ansible_host: 192.168.1.195
      ip: 192.168.1.195
      access_ip: 192.168.1.195
    node3:
      ansible_host: 192.168.1.196
      ip: 192.168.1.196
      access_ip: 192.168.1.196
  children:
    kube-master:
      hosts:
        node1:
        node2:
    kube-node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
